name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version number for the release'
        required: true
        default: '1.0.0'
      snapshot_version:
        description: 'Version number for the next snapshot'
        required: true
        default: '1.0.1-SNAPSHOT'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Update version in pom.xml to release version
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.release_version }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: target/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Package
          path: target/

      - name: Update version in pom.xml to release version
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.release_version }}

      - name: Extract version from pom.xml
        id: extract_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:latest --tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag $IMAGE_NAME:latest $IMAGE_ID:latest
          docker tag $IMAGE_NAME:${{ env.VERSION }} $IMAGE_ID:${{ env.VERSION }}
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:${{ env.VERSION }}

  set-snapshot-version:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update version in pom.xml to snapshot version
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.snapshot_version }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add pom.xml
          git commit -m "Update to snapshot version ${{ github.event.inputs.snapshot_version }}"
          git push
