name: Java CI with Maven

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the image'
        required: true
        type: string

jobs:
  maven:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: target/*.jar

  docker:
    needs: maven
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Package
          path: target/

      - name: Set image name as env
        run: echo "IMAGE_NAME=${{ inputs.image_name }}" >> $GITHUB_ENV

      - name: Extract version from pom.xml
        id: extract_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build multi-platform Docker image
        if: ${{ github.actor != 'renovate[bot]' }}
        run: |
          IMAGE_ID=ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}
          docker buildx build . \
            --file docker/Dockerfile \
            --platform linux/amd64,linux/arm64 \
            --tag $IMAGE_ID:${{ env.VERSION }} \
            --push